# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 23:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('final_date', models.DateField()),
                ('coins', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
            },
        ),
        migrations.CreateModel(
            name='Exchanged_Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('exchanged_date', models.DateField(auto_now=True)),
                ('coupon_exhanged', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanged_cupon', to='publicity.Coupon')),
                ('user_coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exchanged_Coupon',
                'verbose_name_plural': 'Exchanged_Coupons',
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='imageMarks')),
                ('visits', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=140)),
            ],
            options={
                'verbose_name': 'Mark',
                'verbose_name_plural': 'Marks',
            },
        ),
        migrations.AddField(
            model_name='coupon',
            name='mark_coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons_mark', to='publicity.Mark'),
        ),
    ]
